In [15]:
# Database에 접속해서 데이터를 추출한 후에
# DataFrame으로 생성해 보아요!
# 추가적인 library가 필요해요! => sqlalchemy
# base 환경에 설치가 이미 되어 있네요! 따로 설치할 필요가 없어요!
from sqlalchemy import create_engine, text
import numpy as np
import pandas as pd

# sqlalchemy engine을 생성
# 접속할 수 있는 engine을 생성한 후 connect()를 이용해서 Database에 접속!
engine = create_engine('mysql+pymysql://root:1234@localhost:3306/library?charset=utf8mb4')
engine.connect()

# 데이터 추출을 위한 SQL
search_keyword = '파이썬' # 책 제목에 대한 키워드 검색을 하려고 하는거군요!
# LIKE 절 뒤에 keyword는 임시로 지정한거에요!
sql = 'SELECT bisbn, btitle, bauthor, bprice FROM books WHERE btitle LIKE :keyword'

with engine.connect() as connection:
    result = connection.execute(text(sql), {'keyword' : f'%{search_keyword}%'})
    # print(result.fetchone())
    # print(*result.fetchall(), sep='\n')
    df = pd.DataFrame(result.fetchall())

    display(df)

,bisbn,btitle,bauthor,bprice
0,978-89-6848-047-8,파이썬 라이브러리를 활용한 데이터 분석,웨스 맥키니(Wes Mckinney),33000
1,978-89-6848-114-7,파이썬을 활용한 베이지안 통계: 동전 던지기와 하키 승률로 배우는 데이터 분석,앨런 B. 다우니,18000
2,978-89-6848-181-9,파이썬 웹 프로그래밍: Django(장고)로 배우는 쉽고 빠른 웹 개발,김석훈,20000
3,978-89-7914-819-0,Head First Programming : 파이썬으로 처음 배우는 프로그래밍,"폴 배리, 데이빗 그리피스",26000
4,978-89-7914-868-8,Head First Python : 머리에 쏙쏙 들어오는 파이썬 안내서,폴 배리,30000